"""empty message

Revision ID: 69e4dcff7b2a
Revises: 
Create Date: 2023-09-05 12:14:17.200002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e4dcff7b2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subjects',
    sa.Column('subID', sa.Integer(), nullable=False),
    sa.Column('subName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('subID')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('userType', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('bookMaster',
    sa.Column('accNumber', sa.String(length=50), nullable=False),
    sa.Column('bookTitle', sa.String(length=50), nullable=False),
    sa.Column('SubID', sa.Integer(), nullable=False),
    sa.Column('authorName', sa.String(length=50), nullable=False),
    sa.Column('PublisherName', sa.String(length=50), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['SubID'], ['Subjects.subID'], ),
    sa.PrimaryKeyConstraint('accNumber')
    )
    op.create_table('IssueReturn',
    sa.Column('transID', sa.Integer(), nullable=False),
    sa.Column('AccNumber', sa.String(length=50), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('IssueDate', sa.Date(), nullable=False),
    sa.Column('ExpRetDate', sa.Date(), nullable=False),
    sa.Column('ActRetDate', sa.Date(), nullable=False),
    sa.Column('OverdueDays', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AccNumber'], ['bookMaster.accNumber'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('transID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IssueReturn')
    op.drop_table('bookMaster')
    op.drop_table('users')
    op.drop_table('Subjects')
    # ### end Alembic commands ###
